#!/usr/bin/env bash
#created a symbolic link to connect config files seeing that it was listening from different ports, just so it listening to port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restarti
