#!/usr/bin/env bash

sudo service nginx stop

# stop apache since in may interfere nginx
sudo pkill apache2

sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80/listen \[::\]:8080/' /etc/nginx/sites-available/default

sudo nginx -t

# starting nginx with the new nginx user
sudo service nginx start

